### ISSUE TITLE
Loud Sound in Loops

### ISSUE THREAD

**Issue by GabclarexxFR** [SrRapero720/WATERFrAMES#5] opened 2023-06-16 23:40 UTC
Bug :
If a youtube video loop , until we get back in sound range of the frame , the sound will be heard everywhere on the map 

My setup :
Java 17
Forge server 1.19.2-43.2.14
Forge Client 1.19.2 - 43.2.14
WATERFrAMES-1.19.2-1.3.0a
WATERMeDIA 1.1.1

**Comment by SrRapero720** [comment] 2023-06-17 03:55
I can't reproduce it
can you send me a video?

**Comment by GabclarexxFR** [comment] 2023-06-17 20:04
it was another mod who change sound physic who messed  up everything , sorry for the inconvenience

**Comment by SrRapero720** [comment] 2023-06-18 05:32
Sadly bug is real

https://discord.com/channels/486853064284831744/1088664283262496831/1119741755391221810
https://clips.twitch.tv/UnsightlyGorgeousTruffleBrainSlug-pkyHV-eBlMh9l0Wz

**Comment by GabclarexxFR** [comment] 2023-06-18 12:52
hmmm... so why does this problem disappear on my side ?

that is strange , if you need I can give you my server config ( and the modpack I use ) , maybe it can help

**Comment by SrRapero720** [comment] 2023-06-18 12:58
Don't worry, is a VLC issue. is fixed now
https://www.curseforge.com/minecraft/mc-mods/waterframes/files/4594867
https://www.curseforge.com/minecraft/mc-mods/watermedia/files/4594373

This version requires WATERMeDIA 1.2.0 and below of 1.3.0

**Comment by SrRapero720** [comment] 2023-06-19 07:20
still present
is a external mod issue

**Comment by SrRapero720** [comment] 2023-06-19 08:01
same issue, other causes

**Closed as completed by SrRapero720** 2023-06-19 08:01 UTC
Labels: Status: Fixed in Dev
