### ISSUE TITLE
Assertion failed!

### ISSUE THREAD

**Issue by jv20064** [SrRapero720/WATERFrAMES#4] opened 2023-06-12 02:13 UTC
![5a11bee7-f43b-4dc3-a7f9-f720b582044b](https://github.com/SrRapero720/waterframes/assets/136287570/9af978db-3aa0-44e1-80a9-bcec7c92d539)

**Comment by SrRapero720** [comment] 2023-06-12 02:44
This issue is caused by FancyVideo-API. I would suggest that you report it to the creator but I am already working with a better library made by me, which will be used in version 2.0 of the mod.

it's already solved (in dev)

**Comment by SrRapero720** [comment] 2023-06-17 03:54
Fixed in 1.3.0a
https://www.curseforge.com/minecraft/mc-mods/waterframes
https://www.curseforge.com/minecraft/mc-mods/watermedia

REMEMBER UNINSTALL FancyVideo-API AND INSTALL WATERMeDIA (to make it works)

**Closed as completed by SrRapero720** 2023-06-17 03:54 UTC
Labels: Type: Bug, Status: Fixed in Dev
